ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "main"

urlpatterns = [
	path('register/', views.registerPage, name="register"),
	path('accounts/login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),

	path('', login_required(views.IndexView.as_view()), name="home"),
	path('contact/', views.ContactView.as_view(), name="contacto"),
	path('pubAddInfo/', login_required(views.pubAddAnfo.as_view()), name="addinfo"),
	path('Animales/', views.AnimalView.as_view(), name="animal"),
	path('Paisajes/', views.PaisaView.as_view(), name="Paisajes"),
	path('Outfits/', views.OutfitView.as_view(), name="Outfits"),
	path('Tatto/', views.TattoView.as_view(), name="Tatuajes"),
	path('Maquillaje/', views.MaquiView.as_view(), name="Maquillaje"),

	]

ProyectoFinal/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

# Create your models here.

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'

class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Publicaciones(models.Model):

    class Meta:
        verbose_name_plural = 'publicaciones'
        verbose_name = 'publicacion'
        ordering = ["timestamp"]

# Campos que deben ser llenados para las reviews
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="publicacion")
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Publicaciones, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/publicacion/{self.slug}"

ProyectoFinal/main/forms.py
from django import forms
from .models import Publicaciones, ContactProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']

class ReviewForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,			# Campo para el author de la review del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,			# Campo para el Nombre del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,	# Campo para la descripcion
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,			# Campo para el contenido de la review
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()										# Campo para subir una imagen del anime

	class Meta:
		model = Publicaciones
		fields = ['author', 'name', 'description', 'body', 'image']


# Formulario para ingresar un nuevo blog de anime o manga
class PublicacionForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,  
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()

	class Meta:
		model = Publicaciones
		fields = ['author', 'name', 'description', 'body', 'image']


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

ProyectoFinal/main/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages

from .forms import ContactForm, CreateUserForm, PublicacionForm

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from .models import (
		UserProfile,
        Publicaciones
)
# Create your views here.
class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class AnimalView(generic.TemplateView):
	template_name = "main/Animales.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class PaisaView(generic.TemplateView):
	template_name = "main/paisa.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class TattoView(generic.TemplateView):
	template_name = "main/tatto.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class OutfitView(generic.TemplateView):
	template_name = "main/outfits.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class MaquiView(generic.TemplateView):
	template_name = "main/maqui.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)

class pubAddAnfo(generic.FormView):
	template_name = "main/pubaddinfo.html"
	form_class = PublicacionForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)


def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main:login')
			

		context = {'form':form}
		return render(request, 'main/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('main:login')

ProyectoFinal/main/templates/main/Animales.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
 
            </div>
        </section>
    
<section class="page-section bg-light" id="portfolio">
    <div class="grid-container">
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/gatito-mirando-camara-11164.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/husky-en-la-nieve-11146.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/perro-con-sombrero-de-santa-claus-3927.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/cachorro-en-jardin-6683.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/loro-guacamayo-11143.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/tiburon-en-el-agua-3925.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/peces-debajo-del-agua-en-arte-digital-4563.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/panda-en-la-naturaleza-11158.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/arte-digital-de-caballo-4886.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/martin-pescador-ave-7971.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/buho-mirando-8059.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/gato-con-mariposas-arte-digital-4906.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/tigre-rugiendo-5801.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/halcon-en-paisaje-nevado-7274.jpg"/>
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/gato-astronauta-4878.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/ardilla-en-el-bosque-10720.jpg"  />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/amor-de-cisnes-1130.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/lobo-3012.jpg" />
      <img class="grid-item" src="https://www.xtrafondos.com/wallpapers/ciervo-y-la-luna-8785.jpg" />
    </div>
</section>

{% endblock %}

ProyectoFinal/main/templates/main/Maqui.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
 
            </div>
        </section>
    
<section class="page-section bg-light" id="portfolio">
    <div class="grid-container">
      <img class="grid-item" src="https://i.pinimg.com/564x/10/92/42/10924246c86c28dff7c045c08b21b07c.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/e7/a0/81/e7a081cb5dc8257cf5ee8f60f972db03.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/c3/31/dd/c331dd2b306de194e072b9b50dc24b71.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/e9/2f/69/e92f69a4e142065002f257a682400c72.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/8c/da/e9/8cdae9e54ed4b0f9bd90dc6e854c07d4.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/1d/45/46/1d4546becc0970924e57c83d95f802c5.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/6f/93/77/6f937756736e6487eba4681f770a1dcc.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/2e/f5/47/2ef547e49badf44e46fedbd7e7c04812.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/a9/b8/a5/a9b8a59fbba388aadf2497bbabb16196.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/4c/85/1e/4c851e7c36eb2fe0d8683e3417ee0dc5.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/f7/d0/bf/f7d0bf8432c93e8bbf3c2f0d6b4a1909.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/c9/fd/dd/c9fddd0d73398a5ca0c6e6c79d365656.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/9f/88/b6/9f88b6a60468922fb5c95219a5858a1d.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/7c/57/ed/7c57ed9654f6679d0263d3f5a3ebce05.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/1e/64/3a/1e643a2609dfcde74fad892546ed969a.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/12/31/08/12310876c6313597318e627c7fb8d177.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/ed/57/0b/ed570bc98049f16d12ed839431aa565c.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/65/ca/cd/65cacd951bec8f1b14ce4582220ae308.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/2b/c3/5a/2bc35a8947824e4ecb6bab2763994a85.jpg" width="250" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/10/cc/4b/10cc4b8540be4ddc59eb32076f6aa040.jpg" width="250" height="410" />
    </div>
</section>

{% endblock %}

ProyectoFinal/main/templates/main/Outfits.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
 
            </div>
        </section>
    
<section class="page-section bg-light" id="portfolio">
    <div class="grid-container">
      <img class="grid-item" src="https://i.pinimg.com/564x/4a/23/78/4a23781964685f73f36b2c096a944e61.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/35/0f/80/350f80db162e77fec23c050a7d4a22ca.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/d3/4e/4a/d34e4a106eaf6d2dfd76ea948dccd5b5.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/f1/9c/6b/f19c6b1094f3789e7f3097313d7473e1.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/b7/48/f2/b748f2a7f8df895f34f7569f3a8e5cc7.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/66/51/93/665193e52666a4757049483ba3dab917.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/5c/90/96/5c909629943e1ac233a3dcf6c6bfaef2.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/04/33/c8/0433c8441b51483d7bd8d27f76b24cb4.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/7a/d1/ba/7ad1ba86f4ed1213cb36287b4b7e17d7.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/736x/37/9b/86/379b86c75a109d45b434b935eb26f445.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/9c/e8/ed/9ce8ed060c5fd4ae833436f3219b7863.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/70/04/44/7004448f333a5ea6532fccd819fe4938.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/a5/bf/2f/a5bf2f268bf89389879443e3c7e5d1d2.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/a4/47/ed/a447ed9d0b190452853ec5fb4c0d5dfa.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/ab/dc/0c/abdc0c7034c1eee1a436b8b0b662ba33.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/3c/f2/3a/3cf23abba1a7ffcc79763a01e0e78e76.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/90/ca/2f/90ca2ff801505268bdb1d29406405d71.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/06/84/b9/0684b97068cedfe52a710afe4733bf92.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/38/6b/5d/386b5d521811a8126db0afe830337180.jpg" width="230" height="410" />
      <img class="grid-item" src="https://i.pinimg.com/564x/7b/7c/29/7b7c29609fe27dd0d497dac7268cee7e.jpg" width="230" height="410" />
    </div>
</section>

{% endblock %}

ProyectoFinal/main/templates/main/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Agency - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        {% block extend_header%}{%endblock%}
    </head>
    
    <body>
        {% include 'main/partials/messages.html' %}
        {% include 'main/partials/nav.html' %}
    
        {% block content %}
        {% endblock %}
    
        {% include 'main/partials/footer.html' %}


        <!-- Bootstrap core JS-->
        <script src="'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>



        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
        <script>
            var elem = document.querySelector('.grid-container');
            var msnry = new Masonry( elem, {
              // options
              itemSelector: '.grid-item',
              columnWidth: 230,
              gutter: 20,
              isFitWidth: true
            });
         </script>
    </body>
</html>

ProyectoFinal/main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<div class="bg-color">
<section>
    <div class="innerPageBannerCol">
      <div class="container">
        <div class="row g-4 g-md-3  align-items-center">
          <div class="col-md-6">
            <div class="bannerContent">
              <h1 class="xlTitle pb-md-3">Login Section</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  


<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>

                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>

                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn btnPrimary" type="submit" value="Login">
                           </div>
                </form>

            </div>

            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}			
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'main:register' %}" class="ml-2">    Resgitrarse</a>
                </div>
        
            </div>
        </div>
    </div>
</div>

</div>

{% endblock %}
<!-- ================================
End Content
================================= -->

ProyectoFinal/main/templates/main/pubaddinfo.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Add Info</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="PublicacionForm" method="POST" action="{% url 'main:addinfo' %}" enctype="multipart/form-data">
        {% csrf_token %}

            <label for="name">Autor</label>
            {{form.author}}

            <label for="name">Nombre</label>
            {{form.name}}

            <label for="email">Descripcion</label>
            {{form.description}}

            <label for="subject">Mensaje</label>
            {{form.body}}

            <label for="name">Imagen</label>
            {{form.image}}
            <br>
            <br>

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}