ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "main"

urlpatterns = [
	path('register/', views.registerPage, name="register"),
	path('accounts/login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),

	path('', login_required(views.IndexView.as_view()), name="home"),
	path('contact/', views.ContactView.as_view(), name="contacto"),
	path('pubAddInfo/', login_required(views.pubAddAnfo.as_view()), name="addinfo"),
	path('Animales/', views.AnimalView.as_view(), name="animal"),
	path('Paisajes/', views.PaisaView.as_view(), name="Paisajes"),
	path('Outfits/', views.OutfitView.as_view(), name="Outfits"),
	path('Tatto/', views.TattoView.as_view(), name="Tatuajes"),
	path('Maquillaje/', views.MaquiView.as_view(), name="Maquillaje"),

	]

ProyectoFinal/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

# Create your models here.

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'

class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Publicaciones(models.Model):

    class Meta:
        verbose_name_plural = 'publicaciones'
        verbose_name = 'publicacion'
        ordering = ["timestamp"]

# Campos que deben ser llenados para las reviews
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="publicacion")
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Publicaciones, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/publicacion/{self.slug}"

ProyectoFinal/main/forms.py
from django import forms
from .models import Publicaciones, ContactProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']

class ReviewForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,			# Campo para el author de la review del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,			# Campo para el Nombre del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,	# Campo para la descripcion
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,			# Campo para el contenido de la review
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()										# Campo para subir una imagen del anime

	class Meta:
		model = Publicaciones
		fields = ['author', 'name', 'description', 'body', 'image']


# Formulario para ingresar un nuevo blog de anime o manga
class PublicacionForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,  
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()

	class Meta:
		model = Publicaciones
		fields = ['author', 'name', 'description', 'body', 'image']


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

ProyectoFinal/main/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages

from .forms import ContactForm, CreateUserForm, PublicacionForm

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from .models import (
		UserProfile,
        Publicaciones
)
# Create your views here.
class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class AnimalView(generic.TemplateView):
	template_name = "main/Animales.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class PaisaView(generic.TemplateView):
	template_name = "main/paisa.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class TattoView(generic.TemplateView):
	template_name = "main/tatto.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class OutfitView(generic.TemplateView):
	template_name = "main/outfits.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class MaquiView(generic.TemplateView):
	template_name = "main/maqui.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		publicaciones = Publicaciones.objects.filter(is_active=True)

		
		context["publicaciones"] = publicaciones

		return context

class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)

class pubAddAnfo(generic.FormView):
	template_name = "main/pubaddinfo.html"
	form_class = PublicacionForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)


def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main:login')
			

		context = {'form':form}
		return render(request, 'main/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('main:login')

ProyectoFinal/main/templates/main/partials/footer.html
{% load static %}
<!-- Footer-->
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">Copyright Rapidos y Teclosos</div>
            <div class="col-lg-4 my-3 my-lg-0">
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                <a class="link-dark text-decoration-none" href="#!">Terminos de Uso - La Familia es Primero</a>
            </div>
        </div>
    </div>
</footer>

ProyectoFinal/main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

ProyectoFinal/main/templates/main/partials/nav.html
{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    
    <div class="container">
        <a class="navbar-brand" href="{%url 'main:home'%}"><img src="{% static 'assets/logo.jpg' %}" alt="..." width="60" height="125"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="{%url 'main:home'%}"><b>Inicio</b></a></li>
                <li class="dropdown-li">
                  <b>Categorias</b>
                  <ul class="dropdown">
                    <li class="nav-item link-nav" ><a class="nav-link" href="{%url 'main:animal'%}"><b>Animales</b></li>
                    <li class="nav-item link-nav"><a class="nav-link" href="{%url 'main:Outfits'%}"><b>Outfits</b></li>
                    <li class="nav-item"><a class="nav-link" href="{%url 'main:Maquillaje'%}"><b>Maquillaje</b></li>
                    <li class="nav-item"><a class="nav-link" href="{%url 'main:Paisajes'%}"><b>Paisajes</b></li>
                    <li class="nav-item"><a class="nav-link" href="{%url 'main:Tatuajes'%}"><b>Tatuajes</b></li>
                  </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'main:addinfo' %}"><b>Crear</b></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}"><b>USUARIOS</b></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'main:logout' %}"><b>Logout</b></a></li>
            </ul>
        </div>
    </div>
</nav>